version: '3'

services:
  app:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: app1
    volumes:
      - .:/app1
    ports:
      - "8000:8000"